// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Würfel.daten;

#nullable disable

namespace Würfel.Migrations
{
    [DbContext(typeof(WürfelContext))]
    partial class WürfelContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.0");

            modelBuilder.Entity("Würfel.Benutzer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double>("Balance")
                        .HasColumnType("REAL");

                    b.Property<string>("Benutzername")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Passwort")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Benutzer");
                });

            modelBuilder.Entity("Würfel.ScoreBoard", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("BenutzerId")
                        .HasColumnType("INTEGER");

                    b.Property<double>("Bet")
                        .HasColumnType("REAL");

                    b.Property<double>("Win")
                        .HasColumnType("REAL");

                    b.Property<int>("Winstreak")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("BenutzerId");

                    b.ToTable("ScoreBoard");
                });

            modelBuilder.Entity("Würfel.ScoreBoard", b =>
                {
                    b.HasOne("Würfel.Benutzer", "Benutzer")
                        .WithMany()
                        .HasForeignKey("BenutzerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Benutzer");
                });
#pragma warning restore 612, 618
        }
    }
}
